apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
        listen 8080;

        location /api/v1/movies {
            proxy_pass http://movies-service:5100/api/v1/movies;
        }

        location /api/v1/casts {
            proxy_pass http://cast-service:5200/api/v1/casts;
        }

    }