apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesdb
spec:
  selector:
    matchLabels:
      app: moviesdb
  replicas: 1 
  template:
    metadata:
      labels:
        app: moviesdb
    spec:
      containers:
      - name: postegres
        image: postgres:12.1-alpine
        ports:
            - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: movie_db_username
        - name: POSTGRES_PASSWORD
          value: movie_db_password
        - name: POSTGRES_DB
          value: movie_db_dev
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        volumes:
          - name: moviesdb
            persistentVolumeClaim:
              claimName: myclaim
            mountPath: /var/lib/postgresql/data/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  selector:
    matchLabels:
      app: movies
  replicas: 1
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: movies
        image: "hazamor/jenkins-movies:latest"
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: postgresql://movie_db_username:movie_db_password@moviesdbservice:5432/movie_db_dev
        - name: CAST_SERVICE_HOST_URL
          value: http://castservice:5200/api/v1/casts/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: castdb
spec:
  selector:
    matchLabels:
      app: castdb 
  replicas: 1 
  template:
    metadata:
      labels:
        app: castdb
    spec:
      containers:
      - name: postegres
        image: postgres:12.1-alpine
        ports:
            - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: cast_db_username
        - name: POSTGRES_PASSWORD
          value: cast_db_password
        - name: POSTGRES_DB
          value: cast_db_dev
        volumes:
          - name: castdb
            persistentVolumeClaim:
              claimName: myclaim
            mountPath: /var/lib/postgresql/data/


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast
spec:
  selector:
    matchLabels:
      app: cast
  replicas: 1
  template:
    metadata:
      labels:
        app: cast
    spec:
      containers:
      - name: cast
        image: "hazamor/jenkins-cast:latest"
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: postgresql://cast_db_username:cast_db_password@castdbservice:5432/cast_db_dev


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
            - key: nginx.conf
              path: default.conf