apiVersion: v1
kind: Service
metadata:
  name: movies-db-service
  labels:
    app: movies-db-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
  selector:
    app: movies-db

---
apiVersion: v1
kind: Service
metadata:
  name: cast-db-service
  labels:
    app: cast-db-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
  selector:
    app: cast-db


---
apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies
  ports:
    - port: 5100
      targetPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast
  ports:
    - port: 5200
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ngnix-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: ngnix

