apiVersion: v1
kind: Service
metadata:
  name: movies-db-service
  labels:
    app: movies-db-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
  selector:
    app: movies-db
